# Generated by Django 5.1.7 on 2025-04-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="address_line2",
            new_name="full_name",
        ),
    ]
