# Generated by Django 5.1.7 on 2025-04-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="в процес", max_length=50),
        ),
    ]
