name: Keep Render Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Allow manual run too

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render site
        run: curl -s https://momshop.onrender.com > /dev/null 
