name: Keep Render Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Allow manual run too

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render site
        run: curl -s https://nejnosts.onrender.com/ > /dev/null
