# Generated by Django 5.1.7 on 2025-04-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(
                choices=[
                    ("всички цветове", "All colors"),
                    ("бяло", "White"),
                    ("черно", "Black"),
                    ("камел", "Camel"),
                    ("бежав", "Nude"),
                    ("розор", "Pink"),
                    ("син", "Blue"),
                    ("сив", "Сив"),
                ],
                default="",
                max_length=14,
            ),
        ),
    ]
