# Generated by Django 5.1.7 on 2025-04-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_cart_user_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="variant",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
